### ISSUE TITLE
Python3 compatiblity

### ISSUE THREAD

**Issue by ubmarco** [datakortet/yamldirs#1]
Hello,

I'm interested in this project because I have to create various file structures for testing purposes. The library looks great for this purpose.
However, I need to run my code for py27, py34, py35, py36. How do you estimate the efforts of making it compatible with Python 3? When going quickly through the code it looks like there are just print statements which aren't compatible.

Thanks
  Marco

**Comment by thebjorn** [comment]
I've just released Py3 support as v1.1.0 available from PyPI.  Travis tested on 3.4, 3.5, and 3.6.
