### ISSUE TITLE
install_requires misses PyYAML

### ISSUE THREAD

**Issue by ubmarco** [datakortet/yamldirs#3]
Hello,

in setup.py, I find `install_requires=[],` which is empty.

However, the library has a dependency to PyYAML. It's listed in 
```
requires=[
        'PyYAML'
],
```
I have always used `install_requires` instead of `requires`. Maybe that has something to do with the historic distutils / distutils2 / setuptools mess. I just use setuptools and it seems not to react on the `requires` field.

Would you mind using the `install_requires` field instead?

Regards
  Marco

**Comment by thebjorn** [comment]
This is fixed in v1.1.0.  Thanks a lot for reporting, I really appreciate it.

**Comment by ubmarco** [comment]
Thanks @thebjorn for the quick response and the fixes. I already forked your library today doing almost the same fixes as you did, except for basestring where I used the six library. Your solution seems more elegant to me because it has less dependencies.
I'm really grateful for your contribution.

**Comment by thebjorn** [comment]
The six library is probably the way to go in general, but since that was the only issue here (besides print), it seemed like an simple solution.  I found it on StackOverflow: https://stackoverflow.com/a/22679982/75103
